import requests


BASE_URL = "http://127.0.0.1:8000/health/lab-reports"


# ---------------------------------------------------------
# Test Create
# ---------------------------------------------------------

print("\n--- TEST: POST /health/lab-reports ---")

new_report = {
    "report_date": "2026-08-29",
    "collection_date": "2026-08-29",
    "report_datetime": "2026-08-29 09:30:00",
    "report_type": "Blood Work",
    "laboratory_name": "API Test Laboratory",
    "file_name": "api_test_report.pdf",
    "notes": "Created through API test",
}

response = requests.post(
    BASE_URL,
    json=new_report,
)

assert response.status_code == 201, response.text

created_report = response.json()

# Capture the Report_Key generated by the backend.
TEST_REPORT_KEY = created_report["report_key"]

assert TEST_REPORT_KEY.startswith("LAB_20260829_")
assert len(TEST_REPORT_KEY) == 25

assert created_report["report_date"] == "2026-08-29"
assert created_report["file_name"] == "api_test_report.pdf"
assert created_report["laboratory_name"] == "API Test Laboratory"

print(f"Generated Report_Key: {TEST_REPORT_KEY}")
print("PASS: Lab report created through API")


# ---------------------------------------------------------
# Test Get
# ---------------------------------------------------------

print("\n--- TEST: GET /health/lab-reports/{report_key} ---")

response = requests.get(
    f"{BASE_URL}/{TEST_REPORT_KEY}"
)

assert response.status_code == 200, response.text

retrieved_report = response.json()

assert retrieved_report["report_key"] == TEST_REPORT_KEY
assert retrieved_report["report_date"] == "2026-08-29"
assert retrieved_report["laboratory_name"] == "API Test Laboratory"
assert retrieved_report["file_name"] == "api_test_report.pdf"

print("PASS: Lab report retrieved through API")


# ---------------------------------------------------------
# Test List
# ---------------------------------------------------------

print("\n--- TEST: GET /health/lab-reports ---")

response = requests.get(BASE_URL)

assert response.status_code == 200, response.text

reports = response.json()

assert isinstance(reports, list)

assert any(
    report["report_key"] == TEST_REPORT_KEY
    for report in reports
)

print(
    f"PASS: Lab reports listed through API "
    f"({len(reports)} reports found)"
)


# ---------------------------------------------------------
# Test Update
# ---------------------------------------------------------

print("\n--- TEST: PUT /health/lab-reports/{report_key} ---")

updated_data = {
    "report_key": "THIS_KEY_SHOULD_NOT_BE_SAVED",
    "report_date": "2026-08-30",
    "collection_date": "2026-08-30",
    "report_datetime": "2026-08-30 10:45:00",
    "report_type": "Updated Blood Work",
    "laboratory_name": "Updated API Test Laboratory",
    "file_name": "updated_api_test_report.pdf",
    "notes": "Updated through API test",
}

response = requests.put(
    f"{BASE_URL}/{TEST_REPORT_KEY}",
    json=updated_data,
)

assert response.status_code == 200, response.text

updated_report = response.json()

assert updated_report["report_key"] == TEST_REPORT_KEY
assert (
    updated_report["laboratory_name"]
    == "Updated API Test Laboratory"
)

print("PASS: Lab report updated through API")


# ---------------------------------------------------------
# Verify Update
# ---------------------------------------------------------

print("\n--- TEST: VERIFY UPDATE ---")

response = requests.get(
    f"{BASE_URL}/{TEST_REPORT_KEY}"
)

assert response.status_code == 200, response.text

retrieved_updated_report = response.json()

assert retrieved_updated_report["report_key"] == TEST_REPORT_KEY
assert retrieved_updated_report["report_date"] == "2026-08-30"

assert (
    retrieved_updated_report["laboratory_name"]
    == "Updated API Test Laboratory"
)

assert (
    retrieved_updated_report["notes"]
    == "Updated through API test"
)

print("PASS: Updated values verified")


# ---------------------------------------------------------
# Verify Report_Key Immutability
# ---------------------------------------------------------

print("\n--- TEST: REPORT KEY IMMUTABILITY ---")